#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
hi() { 
  clear
  echo -ne "\033[1;33m"
  cat<<-'EOF'
  ,--.
 | oo |
 '--`-'
	EOF
  tput sgr0 bold
  echo "Short cuts:"; tput setaf 4
  alias | sed 's/alias /  /'
  echo ""
  tput sgr0
}

here="$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )"

alias ..='cd ..'
alias ...='cd ../../../'

alias h="history"
alias ls="ls -G"
alias py="python3 -B "
alias vi='nvim --clean -p -c "colorscheme slate" -c "set number" -c "set ts=2 sw=2 sts=2 et" -c "setlocal spell spelllang=en_us" ' 

export BASH_SILENCE_DEPRECATION_WARNING=1
export PATH="$PWD:/opt/homebrew/bin:$PATH"
export PATH="$PWD:/Library/Frameworks/Python.framework/Versions/3.13/bin:$PATH"

EDITOR=vi

here() { cd $1; basename `pwd`; }
PROMPT_COMMAND='echo -ne "🐻 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
hi
